server:
  port: 8889

spring:
  application:
    name: gateway-service
  cloud:
    #Discovery server config
    discovery:
      enabled: true
      # Configuring the Gateway
    gateway:
      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOrigins: "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

  main:
    allow-bean-definition-overriding: true
    web-application-type: reactive

# cors:
#   allowed:
#     origin: http://localhost:4200

management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: always
