services:
    prometheus:
        image: prom/prometheus
        container_name: prometheus
        restart: unless-stopped
        ports:
            - "9090:9090"
        volumes:
            - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

    tempo:
        image: grafana/tempo
        container_name: tempo
        command: ["-config.file=/etc/tempo.yaml"]
        user: "0:0"  # Run as root to avoid permission issues (for testing)
        volumes:
            - ./docker/tempo/tempo.yml:/etc/tempo.yaml:ro
            - ./docker/tempo/tempo-data:/tmp/tempo
        ports:
            - "3200:3200"  # Tempo
            - "9411:9411"  # Zipkin UI

    loki:
        image: grafana/loki:main
        container_name: loki
        command: ["-config.file=/etc/loki/local-config.yaml"]
        ports:
            - "3100:3100"  # Loki

    grafana:
        image: grafana/grafana
        container_name: grafana
        restart: unless-stopped
        ports:
            - "3000:3000"
        links:
            -   prometheus:prometheus
        volumes:
            - ./docker/grafana:/etc/grafana/provisioning/datasources:ro
        environment:
            - GF_SECURITY_ADMIN_USER=admin
            - GF_SECURITY_ADMIN_PASSWORD=password
        depends_on:
            - prometheus
            - tempo
            - loki

    product-service:
        build: .
        container_name: product-service
        restart: always
        ports:
            - "8089:8089"
        environment:
            - SPRING_PROFILES_ACTIVE=dev
        depends_on:
            - prometheus
            - tempo
            - loki